schema:
  properties:
    1:
      title: Shunt value (mOhms)
      name: SHUNT_RESISTANCE
      description: >
        Current sensor shunt resistance (mOhm)
      required: true
      default: 10
      minimum: 1
      maximum: 1000

    2:
      title: Motor resistance (Ohms)
      name: MOTOR_RESISTANCE
      description: >
        Motor armature resistance (Ohm)
      required: true
      default: 95
      minimum: 0
      maximum: 200

    3:
      title: RPM at max voltage without load
      name: RPM_MAX
      description: >
        Maximum speed (RPM)
      required: true
      default: 30000
      minimum: 0
      maximum: 40000

    4:
      title: Max motor power (Watts)
      name: POWER_MAX
      description: >
        Motor power limit threshold (% of nominal power)
      required: true
      default: 230
      minimum: 100
      maximum: 400

    5:
      title: Limit minimal possible RPM
      name: RPM_MIN_LIMIT
      description: >
        Minimal speed (RPM)
      required: true
      default: 3000
      minimum: 0
      maximum: 40000

    6:
      title: Limit maximal possible RPM
      name: RPM_MAX_LIMIT
      description: >
        Maximal speed (RPM)
      required: true
      default: 30000
      minimum: 0
      maximum: 40000

    7:
      title: Proportional term of PID controller
      name: PID_P
      description: >
        Proportional term of PID controllers (% of maximum voltage / % of maximum speed)
      required: true
      default: 1
      minimum: 0
      maximum: 10

    8:
      title: Integral term of PID controller
      name: PID_I
      description: >
        Integral term of PID controllers (% of maximum voltage / % of maximum speed /sec)
      required: true
      default: 1
      minimum: 0
      maximum: 10

    9:
      title: Speed knob zero zone (%)
      name: DEAD_ZONE_WIDTH
      description: >
        Define initial zone where output should be zero (% of max range)
      required: true
      default: 5
      minimum: 0
      maximum: 100
